name: GitHub Actions Demo

on: [push]
jobs:
  My-Github-Action1:
    runs-on: windows-2019
    steps:
      - name: hello
        run: |
          echo "Hello World"
      - name: this will fail
        run: exit1;
