on: push

jobs:
  secrets:
    runs-on: windows-2019
    steps:
    - run: |
        import os
        print(len(os.getenv('MY_VAR')))
      shell: python
      env:
        MY_VAR: ${{ secrets.MY_SECRET }}
      
    
#   - run: echo $MY_VAR
#      env:
#        MY_VAR: ${{ secrets.MY_SECRET }}
